const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs/promises')
const os = require('node:os')
const path = require('node:path')
const { buildEvidenceBrief, recallSnapshotText } = require('../src/evidence-brief')
const { cleanItems, formatAssistance } = require('../src/decision-copy')
const { sha256 } = require('../src/utils')
test('core brief finds late financial values and adverse facts with exact source locations', () => {
  const summary = '目录说明 '.repeat(650) + '2026年半年度 单位：万元 营业收入123,456.78，净利润下降12%，经营活动现金流为-234.56。' + '普通介绍 '.repeat(400)
  const packet = buildEvidenceBrief([{id:'E1',summary}], {queries:['净利润与现金流缺口']})
  assert.match(packet.documents[0].summary, /123,456.78/)
  assert.match(packet.documents[0].summary, /下降12%/)
  assert.match(packet.documents[0].summary, /单位：万元/)
  assert.ok(packet.total_chars <= 2400)
  for(const p of packet.documents[0].core_facts) assert.equal(p.quote, summary.slice(p.start,p.end))
})
test('whole case text budget applies without silently dropping evidence identifiers', () => {
  const evidence = Array.from({length:60},(_,i)=>({id:`E${i}`,summary:'2025年营业收入100万元，成本风险。'.repeat(400)}))
  const packet=buildEvidenceBrief(evidence)
  assert.equal(packet.documents.length,60)
  assert.ok(packet.total_chars<=24000)
  assert.equal(packet.omitted_ids.length,0)
})
test('recall reads hash-verified snapshot and rejects changed content', async () => {
  const root=await fs.mkdtemp(path.join(os.tmpdir(),'brief-'))
  const content='完整披露：营业收入500万元，2026年经营现金流下降20%。'
  await fs.writeFile(path.join(root,'text.bin'),content)
  const item={id:'E',summary:'标题',snapshot_ref:'text.bin',content_sha256:sha256(Buffer.from(content))}
  const [recalled]=await recallSnapshotText([item],root)
  assert.equal(recalled.summary,content)
  assert.equal(recalled.recall_status,'snapshot_retrieved')
  await fs.writeFile(path.join(root,'text.bin'),'changed')
  const [rejected]=await recallSnapshotText([item],root)
  assert.equal(rejected.recall_status,'snapshot_recall_unavailable')
  assert.equal(rejected.summary,'标题')
})
test('assistance normalizes punctuation, deduplicates and separates options', () => {
  assert.deepEqual(cleanItems(['现金流待核实。；','现金流待核实；']),['现金流待核实'])
  const output=formatAssistance(['现金流待核实。；','产能待核实。'])
  assert.ok(!output.includes('。；'))
  assert.ok(!output.includes('现金流待核实'))
  assert.match(output,/详细原因见运行结果/)
})
